# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2018-04-05 04:15
from __future__ import unicode_literals

import datetime
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Documentname',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('doctype', models.CharField(max_length=100)),
                ('docname', models.CharField(db_index=True, max_length=100, unique=True)),
                ('fatherid', models.IntegerField()),
                ('createdate', models.DateTimeField(auto_now=True, db_index=True)),
            ],
            options={
                'verbose_name': '文档字典',
                'verbose_name_plural': '文档字典',
            },
        ),
        migrations.CreateModel(
            name='Question',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('createdate', models.DateTimeField(auto_now=True, db_index=True)),
                ('solvedate', models.DateTimeField(db_index=True, default=datetime.datetime(2018, 4, 10, 12, 15, 23, 424644))),
                ('questionname', models.CharField(max_length=200, unique=True)),
                ('questiondesc', models.TextField(max_length=1000)),
                ('questionlevel', models.CharField(choices=[(1, '普通'), (2, '一般'), (3, '严重'), (4, '紧急')], default='普通', max_length=100)),
                ('questionsource', models.CharField(max_length=100)),
                ('connectoremail', models.EmailField(default='ctt@toowell.cn', max_length=254)),
                ('isclean', models.BooleanField(default=False)),
                ('isdel', models.BooleanField(default=False)),
                ('isspecial', models.NullBooleanField(default=False)),
                ('creator', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='creator_User', to=settings.AUTH_USER_MODEL)),
                ('principal', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='principal_User', to=settings.AUTH_USER_MODEL)),
                ('questionclass', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='question_track.Documentname')),
            ],
            options={
                'verbose_name': '问题',
                'verbose_name_plural': '问题',
            },
        ),
        migrations.CreateModel(
            name='QuestionClass',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('classtype', models.CharField(max_length=100)),
                ('classname', models.CharField(db_index=True, max_length=100, unique=True)),
                ('createdate', models.DateTimeField(auto_now=True, db_index=True)),
            ],
            options={
                'verbose_name': '问题分类',
                'verbose_name_plural': '问题分类',
            },
        ),
        migrations.CreateModel(
            name='QuestionState',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('statetype', models.CharField(max_length=100)),
                ('statename', models.CharField(db_index=True, max_length=100, unique=True)),
                ('fatherid', models.IntegerField()),
                ('allow', models.CharField(max_length=200)),
                ('createdate', models.DateTimeField(auto_now=True, db_index=True)),
            ],
            options={
                'verbose_name': '状态',
                'verbose_name_plural': '状态',
            },
        ),
        migrations.CreateModel(
            name='Solution',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('createdate', models.DateTimeField(auto_now=True, db_index=True)),
                ('solutionname', models.CharField(max_length=200, unique=True)),
                ('solutiondesc', models.TextField(max_length=1000)),
                ('isdel', models.BooleanField(default=False)),
                ('isspecial', models.NullBooleanField(default=False)),
                ('creator', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
                ('questionid', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='question_track.Question')),
            ],
            options={
                'verbose_name': '解决办法',
                'verbose_name_plural': '解决办法',
            },
        ),
        migrations.AddField(
            model_name='question',
            name='questionstate',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='question_track.QuestionState'),
        ),
    ]
