# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2018-04-05 04:43
from __future__ import unicode_literals

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('question_track', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='questionstate',
            name='statecode',
            field=models.IntegerField(default=1),
        ),
        migrations.AlterField(
            model_name='question',
            name='solvedate',
            field=models.DateTimeField(db_index=True, default=datetime.datetime(2018, 4, 10, 12, 43, 43, 184864)),
        ),
    ]
