# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2018-04-05 04:54
from __future__ import unicode_literals

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('question_track', '0002_auto_20180405_1243'),
    ]

    operations = [
        migrations.AlterField(
            model_name='question',
            name='solvedate',
            field=models.DateTimeField(db_index=True, default=datetime.datetime(2018, 4, 10, 12, 54, 10, 732758)),
        ),
        migrations.AlterField(
            model_name='questionstate',
            name='statecode',
            field=models.IntegerField(default=1, unique=True),
        ),
        migrations.AlterField(
            model_name='questionstate',
            name='statename',
            field=models.CharField(db_index=True, max_length=100),
        ),
    ]
