# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2018-04-05 05:15
from __future__ import unicode_literals

import datetime
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('question_track', '0003_auto_20180405_1254'),
    ]

    operations = [
        migrations.AlterField(
            model_name='question',
            name='questionclass',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='question_track.QuestionClass'),
        ),
        migrations.AlterField(
            model_name='question',
            name='solvedate',
            field=models.DateTimeField(db_index=True, default=datetime.datetime(2018, 4, 10, 13, 15, 48, 795003)),
        ),
        migrations.AlterField(
            model_name='questionclass',
            name='classname',
            field=models.CharField(db_index=True, max_length=100),
        ),
    ]
