# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2018-04-09 01:35
from __future__ import unicode_literals

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('question_track', '0004_auto_20180405_1315'),
    ]

    operations = [
        migrations.AlterField(
            model_name='question',
            name='solvedate',
            field=models.DateTimeField(db_index=True, default=datetime.datetime(2018, 4, 14, 9, 35, 30, 635969)),
        ),
    ]
