# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2018-05-18 13:50
from __future__ import unicode_literals

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('question_track', '0005_auto_20180409_0935'),
    ]

    operations = [
        migrations.CreateModel(
            name='Applynew',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('billno', models.CharField(db_index=True, max_length=50, unique=True)),
                ('machinesid', models.CharField(db_index=True, max_length=50, null=True)),
                ('name', models.CharField(max_length=50, null=True)),
                ('province', models.CharField(max_length=20, null=True)),
                ('city', models.CharField(max_length=20, null=True)),
                ('area', models.CharField(max_length=20, null=True)),
                ('billstate', models.IntegerField(db_index=True, null=True)),
                ('billsort', models.CharField(max_length=20, null=True)),
                ('isspecial', models.CharField(max_length=10, null=True)),
                ('agent', models.IntegerField(null=True)),
                ('areacode', models.CharField(db_index=True, max_length=30, null=True)),
                ('creayedate', models.DateTimeField(db_index=True, null=True)),
                ('installdate', models.DateTimeField(db_index=True, null=True)),
                ('a3', models.CharField(max_length=10, null=True)),
                ('A7', models.CharField(max_length=10, null=True)),
            ],
            options={
                'verbose_name': '开户单',
                'verbose_name_plural': '开户单',
            },
        ),
        migrations.AlterField(
            model_name='question',
            name='solvedate',
            field=models.DateTimeField(db_index=True, default=datetime.datetime(2018, 5, 23, 21, 50, 45, 292280)),
        ),
    ]
