# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2018-06-09 00:56
from __future__ import unicode_literals

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('question_track', '0006_auto_20180518_2150'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='questionstate',
            options={'verbose_name': '项目状态', 'verbose_name_plural': '项目状态'},
        ),
        migrations.AlterField(
            model_name='question',
            name='solvedate',
            field=models.DateTimeField(db_index=True, default=datetime.datetime(2018, 6, 14, 8, 56, 50, 679221)),
        ),
    ]
