# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2018-07-07 01:03
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('report', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='applynew',
            options={'verbose_name': '订单', 'verbose_name_plural': '订单'},
        ),
        migrations.AddField(
            model_name='applynew',
            name='ishouse',
            field=models.BooleanField(default=0),
        ),
        migrations.AlterField(
            model_name='applynew',
            name='isspecial',
            field=models.BooleanField(default=0),
        ),
    ]
