# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2018-07-07 04:33
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('report', '0002_auto_20180707_0903'),
    ]

    operations = [
        migrations.AlterField(
            model_name='applynew',
            name='installer',
            field=models.CharField(default='', max_length=20),
        ),
    ]
