# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2018-07-07 04:34
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('report', '0003_auto_20180707_1233'),
    ]

    operations = [
        migrations.RenameField(
            model_name='applynew',
            old_name='name',
            new_name='customer_name',
        ),
    ]
