# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2018-07-05 10:04
from __future__ import unicode_literals

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0003_auto_20180705_1736'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='birday',
            field=models.DateTimeField(default=datetime.datetime.now),
        ),
    ]
